#!/bin/bash

NEW_VERSION="$1"

if [[ -f /usr/local/bin/etcdctl-${NEW_VERSION} ]]; then
  rm -rf /usr/local/bin/etcdctl
  ln -s /usr/local/bin/etcdctl-${NEW_VERSION} /usr/local/bin/etcdctl
  echo "etcdctl change to ${NEW_VERSION}"
else
  echo "sorry, cannot get etcdctl-${NEW_VERSION}"
fi
